Api/Controllers/ConfigController.cs
using System.Threading.Tasks;
using Logic.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Models.ViewModels.Config;

namespace Api.Controllers
{
    [ApiExplorerSettings(IgnoreApi = true)]
    [Route("[controller]")]
    [Authorize(Roles = "Admin")]
    public class ConfigController : Controller
    {
        private readonly IConfigLogic _configLogic;

        public ConfigController(IConfigLogic configLogic)
        {
            _configLogic = configLogic;
        }
        
        [HttpGet]
        [Route("")]
        public IActionResult Index()
        {
            var result = _configLogic.ResolveGlobalConfig();
            
            return View(result);
        }
        
        [HttpPost]
        [Route("")]
        public async Task<IActionResult> UpdateConfig(GlobalConfigViewModel globalConfigViewModel)
        {
            await _configLogic.UpdateGlobalConfig(globalConfigViewModel);

            return RedirectToAction("Index");
        }
    }
}

Api/Views/Config/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Rendering
@using Models.Constants
@model Models.ViewModels.Config.GlobalConfigViewModel

@{
    ViewBag.Title = "Configuration";
    Layout = "_Layout";
    var selectedTheme = Model.Theme;
}

<div class="container">
    @using (Html.BeginForm("UpdateConfig", "Config", FormMethod.Post))
    {
        <div class="form-group">
            @Html.LabelFor(x => x.Theme)
            @Html.DropDownListFor(x => x.Theme, ApplicationConstants.Themes.Select(x => new SelectListItem {Text = x.Key, Value = x.Key, Selected = x.Key == selectedTheme}), new {@class = "form-control"})
        </div>

        <div class="form-group" style="margin: 1rem;">
            <button type="submit" class="btn btn-success">Save Configuration</button>
        </div>
    }
</div>